name: CI/CD workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the project
        run: ./mvnw clean && ./mvnw package
      - name: Test with Maven
        run: mvn test
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the project
        run: ./mvnw clean && ./mvnw package
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag carduin/lo-poti-chat:$(date +%s)
      - name: Push the image to docker hub
        run : docker image push --all-tags carduin/lo-poti-chat
